### ISSUE TITLE
RuntimeError: Video overlay must be 1 or greater

### ISSUE THREAD

**Issue by richardevcom** [r3w0p/ce-gen#1]
Heyo @r3w0p 👋 
Soo.. I tried it and it seems, that there is issues with either path or default video min/max duration if I don't provide one.
Here's the error promt:
```py
PS C:\...\ce-gen> python36 .\main.py
Generating video
Max duration: 18.5s
Traceback (most recent call last):
  File ".\main.py", line 385, in <module>
    main()
  File ".\main.py", line 363, in main
    subclip_max_duration=subclip_max_duration
  File ".\main.py", line 161, in clip_overlay_videos
    raise RuntimeError("Video overlay must be 1 or greater")
RuntimeError: Video overlay must be 1 or greater
```
I run it on Windows 10 (latest) with Python 3.6 without elevated permissions.

**Comment by r3w0p** [comment]
Fixed this with the latest commit. The problem was when the code that would pick a random number of video overlays: it was returning 0 on occasions where only 1 video existed in the directory. I've changed the code to `randint(1, len(list_videos))` now and added exceptions to check for when `list_videos` is of length `0`.
